---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-02-23 - 10:35:13 +0000
  labels:
    app.kubernetes.io/name: quarkusconsumer
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: quarkusconsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkusconsumer
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-02-23 - 10:35:13 +0000
      labels:
        app.kubernetes.io/name: quarkusconsumer
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: jhawkins/quarkusconsumer:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: quarkusconsumer
